from aiogram import types

profileButton = types.KeyboardButton(text='👤 Профиль')
subButton = types.KeyboardButton(text='💰 Оплатить подписку')

mainmenuButton = types.InlineKeyboardButton(text='🏠Вернуться в главное меню', callback_data='call_menu')
returnButton = types.InlineKeyboardButton(text='↩️Вернуться к предыдущему шагу', callback_data='call_back')
fillFormButton = types.InlineKeyboardButton(text='📝Заполнить анкету', callback_data='call_fill')
googleformButton = types.InlineKeyboardButton(text='🗒️Мне неудобно отвечать здесь, я хочу заполнить гугл-форму', callback_data='call_gform')
urlgformButton = types.InlineKeyboardButton(text='Ссылка на гугл-форму', url='https://docs.google.com/forms/d/e/1FAIpQLScmgmFyXUGzf75xIbsSP3xNudbvUaC2Pd6SN1YIy4NXPEhl8A/viewform')
changeButton = types.InlineKeyboardButton(text='✏️Изменить данные', callback_data='call_change')
acceptButton = types.InlineKeyboardButton(text='✅Готово', callback_data='call_accept')
viewButton = types.InlineKeyboardButton(text='📋Посмотреть на анкету', callback_data='call_view')
answerButton = types.InlineKeyboardButton(text='❓Хочу задать вопрос', callback_data='call_answer')
callButton = types.InlineKeyboardButton(text='📞Хочу созвониться', callback_data='call_callback')
#stageButton1 = types.InlineKeyboardButton(text='1', callback_data='call_stage1')
#stageButton2 = types.InlineKeyboardButton(text='2', callback_data='call_stage2')
#stageButton3 = types.InlineKeyboardButton(text='3', callback_data='call_stage3')
#stageButton4 = types.InlineKeyboardButton(text='4', callback_data='call_stage4')
#stageButton5 = types.InlineKeyboardButton(text='5', callback_data='call_stage5')
#stageButton6 = types.InlineKeyboardButton(text='6', callback_data='call_stage6')
#stageButton7 = types.InlineKeyboardButton(text='7', callback_data='call_stage7')
#stageButton8 = types.InlineKeyboardButton(text='8', callback_data='call_stage8')
#stageButton9 = types.InlineKeyboardButton(text='9', callback_data='call_stage9')
#stageButton10 = types.InlineKeyboardButton(text='10', callback_data='call_stage10')
#stageButton11 = types.InlineKeyboardButton(text='11', callback_data='call_stage11')
#stageButton12 = types.InlineKeyboardButton(text='12', callback_data='call_stage12')
#stageButton13 = types.InlineKeyboardButton(text='13', callback_data='call_stage13')
#stageButton14 = types.InlineKeyboardButton(text='14', callback_data='call_stage14')
#stageButton15 = types.InlineKeyboardButton(text='15', callback_data='call_stage15')

numreqButton1 = types.KeyboardButton(text='До 10')
numreqButton2 = types.KeyboardButton(text='10-30')
numreqButton3 = types.KeyboardButton(text='30-50')
numreqButton4 = types.KeyboardButton(text='50-100')
numreqButton5 = types.KeyboardButton(text='100+')

targetButton1 = types.KeyboardButton(text='Увеличение продаж, услуг, товаров')
targetButton2 = types.KeyboardButton(text='Разместить информацию о себе')
targetButton3 = types.KeyboardButton(text='Вся информация в одном месте')
targetButton4 = types.KeyboardButton(text='Запуск курса/марафона')

taplinktypeButton1 = types.KeyboardButton(text='Одностраничный таплинк')
taplinktypeButton2 = types.KeyboardButton(text='Многостраничный таплинк')
taplinktypeButton3 = types.KeyboardButton(text='Интернет-магазин')

deadlineButton1 = types.KeyboardButton(text='Сроки горят')
deadlineButton2 = types.KeyboardButton(text='5-7 дней')
deadlineButton3 = types.KeyboardButton(text='Месяц')
deadlineButton4 = types.KeyboardButton(text='Не принципиально')

budgetButton1 = types.KeyboardButton(text='10 000 - 20 000₽')
budgetButton2 = types.KeyboardButton(text='До 30 000₽')
budgetButton3 = types.KeyboardButton(text='До 40 000₽')
budgetButton4 = types.KeyboardButton(text='До 50 000₽')
budgetButton5 = types.KeyboardButton(text='Бюджет неограничен')

paymentButton1 = types.KeyboardButton(text='Юмани')
paymentButton2 = types.KeyboardButton(text='Сбербанк')
paymentButton3 = types.KeyboardButton(text='Тинькофф')
paymentButton4 = types.KeyboardButton(text='Капуста')
paymentButton5 = types.KeyboardButton(text='Продамус')
paymentButton6 = types.KeyboardButton(text='Оплата на сайте не требуется')
